theme: jekyll-theme-modernist
title: this's homepage title
description: power by github pages
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: ture
github:
  zip_url: http://emperorthree.github.io-main.zip
  another_url: https://github.com/emperorthree